### ISSUE TITLE
"too many redirects" after 417 OTA

### ISSUE THREAD

**Issue by tomholford** [urbit/urbit#6113]
Yesterday I updated a self-hosted moon and planet to the new kelvin version (417).

Both are running vere 1.13, have updates for `garden`, `landscape`, `webterm`, and `bitcoin` set to the pre-release ship.

The moon update went off without a hitch. Same seemingly for the planet, the dojo output seems nominal. However, receiving a "Too many redirects" error message in the browser when attempting to connect to Grid / Landscape.

Based on the troubleshooting conducted so far, this seems to be a cert issue. Will update this ticket once I have more information.

cc: @zalberico

**Comment by tomholford** [comment]
Update:

In the [release notes](https://github.com/urbit/urbit/releases/tag/urbit-os-v2.129-rc4), there's a line about https redirects:
>- Add automatic redirect to https when available.

Wondering if this might be the root cause of the redirect loop. Looking at the Caddy server logs, seeing ~40 "status: [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301)" messages, so a loop potentially between the Urbit binary and Caddy is being triggered.

For context, I am using a docker-compose file like so:
```yml
version: "3.7"

networks:
  web:
    external: true

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ../globs:/globs
    networks:
      - web
  datder-sonnet:
    image: tloncorp/urbit:v1.13
    restart: unless-stopped
    ports:
      - "8080:80"
      - "34343:34343/udp"
    volumes:
      - ~/urbit/datder-sonnet:/urbit/datder-sonnet
    networks:
      - web
    stdin_open: true
    tty: true
    depends_on:
      - caddy

volumes:
  caddy_data:
    external: true
  caddy_config:
```

And a Caddyfile like so:
```Caddyfile
sonnet.page {
	reverse_proxy ops-datder-sonnet-1:80
}
```
