### ISSUE TITLE
Launching a comet fails in v1.15 Docker image, but succeeds in v1.14

### ISSUE THREAD

**Issue by LuciferianInk** [urbit/urbit#6273]
Here is my docker-compose config:
```
  ship:
    image: tloncorp/urbit:v1.15
    command: /bin/urbit -t -c needle
    volumes:
      - urbit:/urbit
    ports:
      - 9667:80
      - 34343:34343

volumes:
  urbit:
```
This is the output it generates:
```
src-ship-1  | boot: found comet ~mosner-lonbud-wistem-nosmul--pidmyn-tobrum-dosned-litzod
src-ship-1  | boot: verifying keys
src-ship-1  | boot: getting sponsor
src-ship-1  | boot: retrieving galaxy table
src-ship-1  | boot: retrieving network domains
src-ship-1  | boot: retrieving keys for sponsor ~litzod
src-ship-1  | boot: retrieving keys for sponsor ~zod
src-ship-1  | boot: parsing %solid pill
src-ship-1  | loom: mapped 2048MB
src-ship-1  | boot: protected loom
src-ship-1  | live: logical boot
src-ship-1  | boot: installed 351 jets
src-ship-1  | ---------------- playback starting ----------------
src-ship-1  | pier: replaying events 1-15
src-ship-1  | wyrd=[~ u=[p=[lal=%lull num=327] q=[~ 328]]]
src-ship-1  | men: %wyrd
src-ship-1  | men: 'arvo: upgrade blocked'
src-ship-1  | mot: %mean
src-ship-1  | mot: %mean
src-ship-1  | pier: (0): play: bail
src-ship-1  | 
src-ship-1  | play: bail: %exit
src-ship-1  | home: bailing out
src-ship-1  | address (nil) out of loom!
src-ship-1  | loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:262
src-ship-1  | home: bailing out
```
Any idea what may be failing here? I've tried a number command line flags, as well as providing my planet key - but they all fail, using this Docker image.

Thanks for any help you can provide.
